### ISSUE TITLE
Rules generation after model rebooting

### ISSUE THREAD

**Issue by lambda-science** [UrbsLab/scikit-ExSTraCS#1]
Hello,

I'm trying to tweak the code of scikit-ExSTraCS to print the list of matching rules for each class for a given prediction. I do this to provide insight about why a prediction was made.

I've been training a model with N=500. After training and rules compaction, a total of 89 rules remains with a total numerosity N=358.
I have pickled my model and rules using:
```python
    trainedModel.export_final_rule_population(
        headers,
        classLabel,
        filename=os.path.join(save_dir, "compacted_rules.csv"),
        RCPopulation=True,
    )
    trainedModel.pickle_model(os.path.join(save_dir, "exstracs_model"))
```
Then when I want to reload my pickl'ed model using
`trained_model = ExSTraCS(reboot_filename="exstracs/N500/exstracs_model")`
It appears that now my trained_model contains now 165 rules for a total numerosity of N=500 (my pre-compaction max numerosity).
Manually loading the Pickle give the same results:
```python
dict_mod = pickle.load(open("exstracs/N500/exstracs_model", "rb"))
len(dict_mod[17]) # classifier set
> 165
```
It this the expected behaviour ?
How can I load my saved model with only the classifier set remaining after rule compaction ?
Am I misunderstanding something about LCS and rule compaction here ?

Thanks,
Have a nice day !

**Edit:** here are my two last learning iterations:
| Iteration| Accuracy | Average Pop. Generality | Macropopulation Size| Micropopulation size
| ------------- | ------------- |-------------| -----| -----|
| 499999     | 0.9| 0.9901|165 | 500 |
| 500000      | 0.9| 0.7099|88   |358 |

**Comment by lambda-science** [comment]
Nevermind, my bad here
From the doc:
> By default, the pickle_model method exports the rule population BEFORE rule compaction. A demo of this is shown below.  

I have to use:  
`model.post_training_rule_compaction()`

**Comment by Aperture77** [comment]
> 
> 
> Nevermind, my bad here
> From the doc:
> 
> > By default, the pickle_model method exports the rule population BEFORE rule compaction. A demo of this is shown below.
> 
> I have to use:
> `model.post_training_rule_compaction()`
